/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns the health status of the application and its components.
         *
         *     Status values:
         *     - `healthy`: All components functioning normally
         *     - `degraded`: Core functionality works but some components have issues
         *     - `unhealthy`: Core functionality is broken
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * OpenAPI specification
         * @description Returns the OpenAPI specification for this API
         */
        get: operations["getOpenApiSpec"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Individual component health status
         * @enum {string}
         */
        ComponentStatus: "healthy" | "degraded" | "unhealthy";
        /**
         * @description Overall health status
         * @enum {string}
         */
        HealthStatus: "healthy" | "degraded" | "unhealthy";
        HealthResponse: {
            status: components["schemas"]["HealthStatus"];
            /**
             * Format: date-time
             * @description Current server time
             */
            timestamp: string;
            /** @description Application version */
            version: string;
            /** @description Server uptime in seconds */
            uptime: number;
            components: {
                database: components["schemas"]["DatabaseHealth"];
                databases: components["schemas"]["DatabasesHealth"];
                jobs: components["schemas"]["JobsHealth"];
                backups: components["schemas"]["BackupsHealth"];
                logs: components["schemas"]["LogsHealth"];
            };
        };
        DatabaseHealth: {
            status: components["schemas"]["ComponentStatus"];
            /** @description Database query response time in milliseconds */
            responseTimeMs: number;
            /** @description Error message if unhealthy */
            message?: string;
        };
        DatabasesHealth: {
            status: components["schemas"]["ComponentStatus"];
            /** @description Total number of PCD databases configured */
            total: number;
            /** @description Number of enabled databases */
            enabled: number;
            /** @description Number of databases with compiled cache */
            cached: number;
            /** @description Number of disabled databases (compilation errors) */
            disabled: number;
            /** @description Additional status information */
            message?: string;
        };
        JobsHealth: {
            status: components["schemas"]["ComponentStatus"];
            /** @description Last run time for each job */
            lastRun?: {
                [key: string]: string | null;
            };
            /** @description Additional status information */
            message?: string;
        };
        BackupsHealth: {
            status: components["schemas"]["ComponentStatus"];
            /** @description Whether backups are enabled */
            enabled: boolean;
            /**
             * Format: date-time
             * @description Timestamp of last backup
             */
            lastBackup?: string | null;
            /** @description Number of backup files */
            count?: number;
            /** @description Total size of all backups in bytes */
            totalSizeBytes?: number;
            /** @description Configured retention period in days */
            retentionDays?: number;
            /** @description Additional status information */
            message?: string;
        };
        LogsHealth: {
            status: components["schemas"]["ComponentStatus"];
            /** @description Total size of log files in bytes */
            totalSizeBytes?: number;
            /** @description Number of log files */
            fileCount?: number;
            /**
             * Format: date
             * @description Date of oldest log file
             */
            oldestLog?: string | null;
            /**
             * Format: date
             * @description Date of newest log file
             */
            newestLog?: string | null;
            /** @description Additional status information */
            message?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Health check response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getOpenApiSpec: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenAPI specification */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
}
