name: 📌 Roadmap
description: Planned feature or improvement (maintainer use)
labels: ["type: feature", "source: maintainer"]

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: What and why
    validations:
      required: true

  - type: input
    id: related
    attributes:
      label: Related issues
      placeholder: "#123, #456"
